### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by seenthestars** [z1069614715/yolo-gradcam#1]
博主直接拉取你的yolov5_heatmap.py到v5 6.1版本报错，请问这要怎么解决？版本不兼容吗
Transferred 348/349 items
  0%|          | 0/378 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\PycharmProjects\yolov5-6.1\yolov5_heatmap.py", line 117, in <module>
    model(r'D:\PycharmProjects\yolov5-6.1\test\01.png', 'result')
  File "D:\PycharmProjects\yolov5-6.1\yolov5_heatmap.py", line 77, in __call__
    post_result[i, 0].backward(retain_graph=True)
  File "E:\Program Files\conda_data\envs\yolov5-5.0\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "E:\Program Files\conda_data\envs\yolov5-5.0\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 3, 15, 20, 9]], which is output 0 of SigmoidBackward0, is at version 2; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

Process finished with exit code 1

**Comment by z1069614715** [comment]
请在v7.0使用
